### ISSUE TITLE
Can't access the dataset link

### ISSUE THREAD

**Issue by XiaRho** [jzuern/heatnet-pub#1]
Thank you for your wonderful work. I am unable to access and download the dataset you provided http://thermal.cs.uni-freiburg.de/. The link you provided seems to be invalid. I would appreciate any assistance in resolving this issue so that I can access and download the dataset as intended. Thank you for your help.

**Comment by jzuern** [comment]
Sorry for the late reply. We are currently investigating these server issues. Can you download the files via
```bash
wget http://aisdatasets.informatik.uni-freiburg.de/freiburg-thermal-segmentation/train.zip
wget http://aisdatasets.informatik.uni-freiburg.de/freiburg-thermal-segmentation/test.zip
```
?

**Comment by XiaRho** [comment]
This link is working, thanks a lot, I will close this issue.
